name: restaurant-api-workflow

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Check out repository code
    uses: actions/checkout@v7
  - name: Install java
    uses: actions/setup-java@v5
    with:
     distribution: 'temurin'
     java-version: '21'
     cache: 'maven'
  - name: Build app with Maven
    run: mvn -B clean package -DskipTests
    


